### ISSUE TITLE
Some not fully qualified imports breaks Storybook using Webpack 5

### ISSUE THREAD

**Issue by Khauri** [marko-js/tags-api-preview#7]
### Details

This might actually be an issue with the @storybook/marko webpack 5 config, but I decided to post the issue here because I wasn't sure if this is an intentional feature of @storybook/marko as it has to do with an intentional breaking change in webpack 5 concerning ESM.

Basically, storybook throws this error when using some basic features of the tags API. I haven't determined which feature actually breaks this, but if you look at my [reproduction repo](https://github.com/Khauri/turbo-octo-guide) it doesn't really take much to cause it.

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../../util/patch-lifecycle' in '/Users/khauri/Documents/projects/marko-storybook-bug/node_modules/@marko/tags-api-preview/dist/components/return'
Did you mean 'patch-lifecycle.mjs'?
BREAKING CHANGE: The request '../../util/patch-lifecycle' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

This error basically suggests that ann import/require statement somewhere in this package needs to be fully qualified (ie include the file extension).

### Expected Behavior

Compilation should work without error. 

### Actual Behavior

An error is thrown causing storybook to not boot up.

### Possible Fix

One solution is to fully qualify the imports in this repository.

I was also able to work around this by adding this to the default config in `.storybook/main.js`:

```
webpackFinal: config => {
    // This fixes the problem, but not sure if it should be default in the config
    config.module.rules.unshift({
      test: /\.m?js/,
      resolve: {
        fullySpecified: false,
      },
    });
    return config;
}
```

So I believe a similar config could be added to @storybook/marko, but I don't know what implications that has broadly.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

See: https://github.com/Khauri/turbo-octo-guide

### Stack Trace

</details>

**Comment by DylanPiercey** [comment]
@Khauri I've reverted the output to CJS only until I'm able to find a better work around for outputting both ESM and CJS.
