### ISSUE TITLE
Support for named body content

### ISSUE THREAD

**Issue by dephiros** [marko-js/tags-api-preview#8]
### Description
From the `vite` example, I tried to add some tag API syntax to `app-layout.marko` but received the error that I cannot mix class and tag API at `input.head`. When I tried to convert `input.head` using the new `attrs` tag, that does not seem to work

FROM:
```
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <${input.head}/>
  </head>
```
TO:
```
<attrs/{ head, body } />
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <${head}/>
  </head>
```

### Why
Allow named body content and tag API to be used together. Could be I am just missing an obvious syntax here

### Possible Implementation & Open Questions
N/A

**Comment by DylanPiercey** [comment]
@dephiros sorry for the delayed reply on this one. Named body content should be working as used in the examples you've shared. If you are seeing an error saying "Mixed class / tags api" then there is likely some other incompatibility in the template.

Are you able to share the full error and template?

**Comment by dephiros** [comment]
> @dephiros sorry for the delayed reply on this one. Named body content should be working as used in the examples you've shared. If you are seeing an error saying "Mixed class / tags api" then there is likely some other incompatibility in the template.
> 
> Are you able to share the full error and template?

Hi @DylanPiercey , thank you for the response. I was playing with this a while ago and don't have that example anymore. Maybe this is no longer an issue.
