### ISSUE TITLE
get tag not updating on changes from set tag

### ISSUE THREAD

**Issue by Khauri** [marko-js/tags-api-preview#9]
### Details

The `<get>` tag isn't receiving the changes from the `<set>` tag whenever the `<set>` tag has its value updated.

### Expected Behavior

The `<get>` tag should update its returned value upon the `<set>` tag's context changing.

### Actual Behavior

Nothing happens and nothing is updated.

### Possible Fix

Firstly, It seems like there's a typo [in this line](https://github.com/marko-js/tags-api-preview/blob/main/src/components/get/index.marko#L29).

```js
        this.sub = this.subscribeTo(this.provider).on("___change", this.sync);
```

should be:

```js
        this.sub = this.subscribeTo(this.provider).on("___changed", this.sync);
```

in order to [match the name of event that's emitted from the `<set>` tag.](https://github.com/marko-js/tags-api-preview/blob/main/src/components/set/index.marko#L33).

Additionally, in the `<set>` tag, because `component.___rendered` is set to `true`, the `___changed` event is only ever emitted once and not on each render. I don't know if this is intentional and the `___changed` event is intended to be fired elsewhere (I could not find any other references in the codebase), but changing:

```js
  if (typeof window === "object" && !component.___rendered) {
    component.___rendered = true;
    component.emit("___changed");
  }
```

to

```js
  if (typeof window === "object" && typeof component.emit === 'function') {
    component.emit("___changed");
  }
```
seems to solve the issue and allows the tag to update.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): Node 12
- Operating System and version (desktop or mobile): MacOS
- Link to your project:

### Steps to Reproduce

https://codesandbox.io/s/twilight-wind-wojol?file=/components/test.marko

### Stack Trace

</details>

**Comment by DylanPiercey** [comment]
Greatly appreciate you taking the time to look into this. I'll try my best to get a patch out soon! Surprised our test suite missed this case, but guess we must not be testing when a child is not rerendered with its parent.

**Comment by DylanPiercey** [comment]
Scratch that, you made a PR already!
